### ISSUE TITLE
How to integrate nao_full_py with moveit_planner without nao_gazebo_plugin?

### ISSUE THREAD

**Issue by Yanzqing** [ros-naoqi/nao_virtual#16]
I am using nao_full_py.launch to controll my NAO robot. I want to use moveit to controll NAO through naoqi,  and i am wondering how i can load nao_trajectory_controller without nao_gazebo_plugin? Can you offer some advices? Thank you!

**Comment by nlyubova** [comment]
did you try it when launching the demo ? :
roslaunch nao_moveit_config demo.launch
