### ISSUE TITLE
Connection Refused. QiMessaging Error

### ISSUE THREAD

**Issue by blackvitriol** [ros-naoqi/nao_virtual#23]
Hey devs, sorry for this noob question, but when I was following the tutorial, I got stuck at the testing part:

When I run 
roslaunch naoqi_driver naoqi_driver.launch nao_ip:=127.0.0.1 (virtual robot on Choregraph)
I get this error:

```
SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /
    naoqi_driver (naoqi_driver/naoqi_driver_node)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[naoqi_driver-1]: started with pid [13854]
[W] 1494699559.026087 13858 qimessaging.transportsocket: connect: Connection refused
terminate called after throwing an instance of 'qi::FutureUserException'
  what():  System error: Connection refused
================================================================================REQUIRED process [naoqi_driver-1] has died!

```
How do I fix this ?

**Comment by nlyubova** [comment]
Hello,
I am not sure if it should work with a virtual robot in Choregraphe. Which tutorial did you follow?

**Comment by blackvitriol** [comment]
Did not follow a tutorial this time, was experimenting.

**Comment by nlyubova** [comment]
You can actually simulate a virtual robot with Naoqi.
For this, you need to download an SDK from community.aldebaran.com and start it like this:
~/naoqi/naoqi-sdk/naoqi --verbose --broker-ip 127.0.0.1

Then, you can connect to your virtual robot as you done with Naoqi_driver.

**Comment by blackvitriol** [comment]
Sorry for the rebump, can someone help me with this error:

Receiving information about robot model
[W] 19699 qimessaging.remoteobject: Return signature might be incorrect depending on the value, from m to s
terminate called after throwing an instance of 'qi::FutureUserException'
  what():  	ALMemory::getData
	Data not found RobotConfig/Body/Type

**Comment by nlyubova** [comment]
hello,
how did you get this error?  which package did you run?

**Comment by brain0071** [comment]
> hello, how did you get this error? which package did you run?

I am using ubuntu18.04.
I have run "roscore", and ~/naoqi/naoqi-sdk/naoqi --verbose --broker-ip 127.0.0.1. then "I run roslaunch naoqi_driver naoqi_driver.launch nao_ip:=127.0.0.1", I got this error:
```
Receiving information about robot model
terminate called after throwing an instance of 'qi::FutureUserException'
  what():  	ALMemory::getData
	Data not found RobotConfig/Body/Type
```
