### ISSUE TITLE
Robot's camera don't see robot parts

### ISSUE THREAD

**Issue by keulYSMB** [ros-naoqi/nao_virtual#6]
The RGB cameras give a good rendering of the surrounding environment. But the robots parts seem to be invisible. When a robot part is in the field of view of the camera, it doesn't appear on the output image.
(cf. attached screenshot)
![camerabuggazebo](https://cloud.githubusercontent.com/assets/6644208/6324258/9771d25a-bb05-11e4-95b4-5b2c42264509.png)

**Comment by vrabaud** [comment]
yeah, I think that is somewhat normal: I just added optical frames and those are the ones you should use for your cameras and for the publishers. They are just rotated from the camera frames.
Look at my recent commits: https://github.com/ros-naoqi/naoqi_bridge/commit/cfcb69e10777a1771df6aef9ea57305643ffe06f and before that: https://github.com/ros-naoqi/naoqi_bridge/commit/126d32a7513fa9b7e2a3124c6262a6ad262418b7
E.g., if you use the Camera plugin, it now works in RViz (with a real robot).

**Comment by keulYSMB** [comment]
I'll try that soon but I'm afraid the image won't have the right orientation anymore.
I just updated my sources and it seems that urdf are corrupted since a recent update. robot state publisher is unable to publish tf. I'm not able to visualize the urdf in Rviz.
I'll let you know (once this is fixed) if using the optical frames solve the problem.

**Comment by keulYSMB** [comment]
Ok I finally figured it out, it is a mater of distance and not a matter of frames. the robot is able to see his feet but not his arms. It's juste dependent on the paramters "near" and "far" given to the plugin. 
We would just have to tune them I guess. It was 30cm so regarding the size of NAO it was a huge dead zone.

**Comment by vrabaud** [comment]
I love it when a plan comes together.
