### ISSUE TITLE
Meshes not found

### ISSUE THREAD

**Issue by awesomebytes** [ros-naoqi/nao_virtual#7]
This is probably a temporary problem while you are updating stuff but trying to checkout all the last packages and launching a simulated nao (football field one or simple empty world):

    roslaunch nao_gazebo_plugin nao_gazebo.launch

Gives:

Error [SystemPaths.cc:367] File or path does not exist["/home/sam/nao_ws/src/nao_meshes/nao_meshes/meshes/V40/Torso.dae"]
Error [Visual.cc:2133] No mesh specified
Error [SystemPaths.cc:367] File or path does not exist["/home/sam/nao_ws/src/nao_meshes/nao_meshes/meshes/V40/Torso_0.10.stl"]
Error [Visual.cc:2133] No mesh specified
Error [SystemPaths.cc:367] File or path does not exist["/home/sam/nao_ws/src/nao_meshes/nao_meshes/meshes/V40/HeadYaw.dae"]
Error [Visual.cc:2133] No mesh specified
Error [SystemPaths.cc:367] File or path does not exist["/home/sam/nao_ws/src/nao_meshes/nao_meshes/meshes/V40/HeadPitch.dae"]
Error [Visual.cc:2133] No mesh specified
Error [SystemPaths.cc:367] File or path does not exist["/home/sam/nao_ws/src/nao_meshes/nao_meshes/meshes/V40/HeadYaw_0.10.stl"]
...
Etc

I see that nao_meshes (nao_meshes/nao_meshes/meshes/V40) contains now collision and visual. And that path has not been updated in the generated URDF. As a temporal workaround I just copied everything from the visual and collision folder to one folder up (the V40 folder). But there are still meshes missing and it's trying to go back in the path wrongly:

Error [Material.cc:93] Unable to find texture[../../../texture/textureNAO.png] in path[/home/sam/nao_ws/src/nao_meshes/nao_meshes/meshes/V40]

(should be ../../texture/textureNAO.png)

And after this, well, the robot falls into the ground infinitely. But that's another problem (related to not finding collision meshes maybe?).

Also a last extra, the contents of my current rosinstall:

- git: {local-name: nao_dcm_robot, uri: 'https://github.com/ros-aldebaran/nao_dcm_robot'}
- git: {local-name: nao_extras, uri: 'https://github.com/ros-naoqi/nao_extras'}
- git: {local-name: nao_moveit_config, uri: 'https://github.com/ros-naoqi/nao_moveit_config'}
- git: {local-name: nao_robot, uri: 'https://github.com/ros-naoqi/nao_robot'}
- git: {local-name: nao_virtual, uri: 'https://github.com/ros-naoqi/nao_virtual'}
- git: {local-name: nao_viz, uri: 'https://github.com/ros-naoqi/nao_viz'}
- git: {local-name: naoqi_bridge, uri: 'https://github.com/ros-naoqi/naoqi_bridge'}
- git: {local-name: pal_gazebo_plugins, uri: 'https://github.com/pal-robotics/pal_gazebo_plugins'}
- git: {local-name: pal_msgs, uri: 'https://github.com/pal-robotics/pal_msgs'}
- git: {local-name: roboticsgroup_gazebo_plugins, uri: 'https://github.com/roboticsgroup/roboticsgroup_gazebo_plugins'}

**Comment by awesomebytes** [comment]
Ok, I was using
https://github.com/vrabaud/nao_meshes_generator
and not
https://github.com/ros-naoqi/nao_meshes_installer

So I was using old ones, my bad, sorry. Closing. I'll try again another day!

**Comment by vrabaud** [comment]
actually, you should use that package:
https://github.com/ros-naoqi/nao_meshes/
please follow the README. If you are on Ubuntu, just install the package, it is easier.
